In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
df=pd.read_csv("/kaggle/input/santander-product-recommendation/train_ver2.csv.zip",nrows=1000000)

/tmp/ipykernel_32/899733812.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/kaggle/input/santander-product-recommendation/train_ver2.csv.zip",nrows=1000000)

In [3]:
df.head()

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,2015-01-28,1375586,N,ES,H,35,2015-01-12,0.0,6,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
1,2015-01-28,1050611,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
2,2015-01-28,1050612,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
3,2015-01-28,1050613,N,ES,H,22,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
4,2015-01-28,1050614,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0

In [4]:
df.isnull().sum()d

SyntaxError: invalid syntax (3699854484.py, line 1)

In [ ]:
 #Lots of 10782 values may be they all are from same rows

In [ ]:
#Basic Cleansing of data before EDA

In [ ]:
df['ult_fec_cli_1t']

In [ ]:
#ult_fec_cli_1t
#This column has max nan. This column refers to Last date as a primary customer
#hence we cannot drop this column
#hence we replace all non-null values a to1 (that the intended person is primary) and null value as 0
df['ult_fec_cli_1t'] = df['ult_fec_cli_1t'].replace(np.nan, 0)
df['ult_fec_cli_1t'] = df['ult_fec_cli_1t'].where(df['ult_fec_cli_1t'] == 0, 1)

In [ ]:
#conyuemp
#which refers to spouse index is dropped ascit is not nice to impute data which are missing in the majority.
df.drop(['conyuemp'], axis = 1, inplace = True)

In [ ]:
#renta or “Gross income of household” is an important feature on deciding a customer’s economical
#status  we cannot drop this column.so will be imputing MODE value on the NAN cells.
df['renta'] = df['renta'].fillna(df['renta'].mode()[0])

In [ ]:
#cod_prov Customer Provision is an important value since according to Region, people's financial exposure is judged. 
#if they are in big city or not 
#df.dropna(subset=['cod_prov'], how='all',inplace=True)Hence it is better to drop all the records whose Provisional code is not mentioned
df.dropna(subset=['cod_prov'], how='all',inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna(subset=['sexo'], how='all', inplace=True)
df.dropna(subset=['canal_entrada'], how='all', inplace=True)
df.dropna(subset=['segmento'], how='all', inplace=True)

In [ ]:
#Exploratory Data Analysis

In [ ]:
sns.countplot(data=df, x="age")
plt.xlabel("Age")
plt.ylabel("Count")
plt.title("Countplot of Age")
plt.show()

In [ ]:
plt.figure(figsize=(8, 5))  
sns.histplot(data=df, x="age")
plt.title("Distribution Plot of age")
plt.show()

In [ ]:
df['age'] = df['age'].astype(int)

In [ ]:
#In order to do get a better insight into the data, I added bin_ranges column to the dataset.

In [ ]:
bin_ranges = [0, 18, 25, 35, 45, 60, 80, 100, 120]
df['age_bins'] = pd.cut(df['age'], bins=bin_ranges)
sns.countplot(data=df, x='age_bins')
plt.xlabel('Age Bins')
plt.ylabel('Count')
plt.title('Countplot of Age Bins')
plt.xticks(rotation=45)  
plt.show()

In [ ]:
age_bins = [0, 18, 25, 35, 45, 60, 80, 100, 120]
df['Binned_No'] = pd.cut(df['age'], bins=age_bins, labels=False)

In [ ]:
df['age_bins'].value_counts().sort_index()

In [ ]:
#Above 100, the customer count is very less, followed by an age of below 20.
#The highest customer is at age 22, followed by 23 and 24
#There is a nice age distribution from 21 to 25 and from age 37 to 52
#Eventually, the number of customers decreased gradually from age 44.
#Normal distribution for say 18-to 30 and 30 to 100

In [ ]:
df.info()

In [ ]:
#ind_empleado
#Meaning: Employee index: A active, B ex employed, F filial, N not employee, P/S passive.
sns.countplot(data=df, x="ind_empleado")
plt.xlabel("ind_empleado")
plt.ylabel("Count")
plt.show()

In [ ]:
#’N’ has a major chunk of data

In [ ]:
#pais_residencia
#Meaning: Two-digit Customer’s Country residence Loose Translation: country of residence.
sns.countplot(data=df, x="pais_residencia")
plt.xlabel("pais_residencia")
plt.ylabel("Count")
plt.show()

In [ ]:
#‘ES’ for Spain, has a major share of data.
#Note: As seen above ‘ind_empleado’ and ‘pais_residencia’ data is highly imbalanced,.

In [ ]:
#SEXO customer’s Gender H-female (Hembra) / V-male (Varon)
plt.figure(figsize=(6, 4)) 
sns.countplot(data=df, x="sexo")
plt.xlabel("sexo")
plt.ylabel("Count")
plt.title("Countplot of Sex")
plt.show()

In [ ]:
#In the Age group 18–25, Female customers are more than male customers. 
#This is the only time it happened across all the age groups.

In [ ]:
#tiprel_1mes
#Customer relation type at the beginning of the month, A (active), I (inactive), P (former customer), R (Potential).
plt.figure(figsize=(6, 4))
sns.countplot(data=df, x="tiprel_1mes")
plt.xlabel("tiprel_1mes")
plt.ylabel("Count")
plt.title("Countplot")
plt.show()

In [ ]:
#There are only three categories for this feature in our dataset. Active (543912), Inactive(438141) and Primary(2).

In [ ]:
#ind_actividad_cliente
# Activity index (1 — active customer; 0 — inactive customer).
plt.figure(figsize=(6, 4)) 
sns.countplot(data=df, x="ind_actividad_cliente")
plt.xlabel("ind_actividad_cliente")
plt.ylabel("Count")
plt.show()

In [ ]:
Relatively this feature is a balance feature, having 554649(Active Customer) and 427406 (Inactive Customer).

In [ ]:
#segmento
#(segmentation: 01 — VIP, 02 — Individuals 03 — college graduated)
plt.figure(figsize=(6, 4)) 
sns.countplot(data=df, x="segmento")
plt.xlabel("segmento")
plt.ylabel("Count")
plt.show()

In [ ]:
#PARTICULAR has the highest Customer count (652027) followed by UNIVERSITY (273051) and TOP has the least segmentation(56977).

In [ ]:
#renta
# Gross income of the householdplt.
plt.figure(figsize=(8, 5))  
sns.histplot(data=df, x="renta", color="steelblue")
plt.xlabel("Renta")
plt.ylabel("Frequency")
plt.title("Distribution Plot of Renta")
plt.show()

In [ ]:
plt.figure(figsize=(8, 5))  # Set the size of the plot
sns.histplot(data=np.log1p(df['renta']), color="steelblue", kde=True)
plt.xlabel("Log Renta")
plt.ylabel("Frequency")
plt.title("Distribution Plot of Log Renta")
plt.show()

In [ ]:
bins = [0, 300, 3000, 30000, 300000, 3000000, 30000000, 300000000]
labels = ['0-300', '300-3000', '3000-30000', '30000-300000', '300000-3000000', '3000000-30000000', '30000000-300000000']

df['renta_bins'] = pd.cut(df['renta'], bins=bins, labels=labels)
sns.countplot(data=df, x='renta_bins')
plt.xlabel('Renta Bins')
plt.ylabel('Count')
plt.title('Countplot of Renta Bins')
plt.xticks(rotation=45)  
plt.show()

In [ ]:
#Customers having income between (30000, 300000] has the major Customer chunk. 
#There were no customers whose income was either less than 300 Euro or 30,000,000 Euro.

#Products

In [ ]:
#ind_cco_fin_ult1(Current Accounts)

count_by_age = df.groupby('age_bins')['ind_cco_fin_ult1'].sum()
count_by_renta = df.groupby('renta_bins')['ind_cco_fin_ult1'].sum()

# Plot Count by Age Bin
plt.figure(figsize=(10, 6))
sns.barplot(x=count_by_age.index, y=count_by_age.values)
plt.xlabel('Age Bin')
plt.ylabel('Count')
plt.title('Count of ind_cco_fin_ult1 by Age Bin')
plt.show()

# Plot Count by Renta Bin
plt.figure(figsize=(10, 6))
sns.barplot(x=count_by_renta.index, y=count_by_renta.values)
plt.xlabel('Renta Bin')
plt.ylabel('Count')
plt.xticks(rotation=45)  
plt.title('Count of ind_cco_fin_ult1 by Renta Bin')
plt.show()

In [ ]:
#This is the Most popular Product avail by Customers.
#Max Current accounts are opened by Customers who fall under the age bin 18 to 25.
#Maximum Customer opened Current accounts are in the income range from 30000 to 300000 Euro.

In [ ]:
def plot_against_age_renta(product):
        count_by_age = df.groupby('age_bins')[product].sum()
        count_by_renta = df.groupby('renta_bins')[product].sum()
        
        # Plot Count by Age Bin
        plt.figure(figsize=(10, 6))
        sns.barplot(x=count_by_age.index, y=count_by_age.values)
        plt.xlabel('Age Bin')
        plt.ylabel('Count')
        plt.show()

        # Plot Count by Renta Bin
        plt.figure(figsize=(10, 6))
        sns.barplot(x=count_by_renta.index, y=count_by_renta.values)
        plt.xlabel('Renta Bin')
        plt.ylabel('Count')
        plt.xticks(rotation=45)  
        plt.show()

In [ ]:
#ind_cno_fin_ult1(Payroll Account)
plot_against_age_renta('ind_cno_fin_ult1')

In [ ]:
#Max Payroll accounts are opened by customers who fall under the age bin 45 to 60 and have an income range 
#from 30000 to 300000 Euro.

In [ ]:
#ind_ctju_fin_ult1(Junior Account)
plot_against_age_renta('ind_ctju_fin_ult1')

In [ ]:
#Max Junior accounts are opened by customers who fall under the age bin of below 18 and, 
#have income range from 30000 to 300000 Euro .

In [ ]:
#ind_dela_fin_ult1(Long-term deposits)
plot_against_age_renta('ind_dela_fin_ult1')

In [ ]:
#Max Long-term accounts are opened by
#customers who fall under the age bin 45 to 60, and
#has income range from 30000 to 300000 Euro.

In [ ]:
#ind_plan_fin_ult1(Pensions)
plot_against_age_renta('ind_plan_fin_ult1')

In [ ]:
#Max Pensions accounts are opened by
#customers who fall under the age bin 45 to 60, and
#has income range from 30000 to 300000 Euro.

In [ ]:
#ind_reca_fin_ult1(Taxes)
plot_against_age_renta('ind_reca_fin_ult1')

In [ ]:
#Max Taxes accounts are opened by customers
#who fall under the age bin 35 to 45 and
#has an income range from 30000 to 300000 Euro.

In [ ]:
#Feature encoding.

In [ ]:
df['ind_empleado'].unique()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['ind_empleado'] = le.fit_transform(df['ind_empleado'])
df['ind_empleado'].unique()

In [ ]:
def label_encode(df,col_name):
    df[col_name] = df[col_name].astype('str')
    le = LabelEncoder()
    df[col_name] = le.fit_transform(df[col_name])

In [ ]:
#label encode columns
label_encode_cols = ['pais_residencia', 'sexo','tiprel_1mes','indresi','indext','canal_entrada','indfall','nomprov','segmento']
for col in label_encode_cols:
     label_encode(df,col)

In [ ]:
df = df.drop(["tipodom"], axis=1)

In [ ]:
# Compute the correlation matrix
corr_matrix = df.iloc[:,:23].corr()

# Create a correlation heatmap
plt.figure(figsize=(24, 18))  # Optional: Set the figure size
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap of Features')
plt.show()

In [ ]:
df = df.drop(["ind_actividad_cliente", "cod_prov"], axis=1)

In [ ]:
df = df.drop(["fecha_dato"], axis=1)
df = df.drop(["fecha_alta"], axis=1)

In [ ]:
df.isnull().sum()

In [ ]:
df = df.drop(['ind_nomina_ult1', 'ind_nom_pens_ult1'], axis=1)

In [ ]:
f_prefix = 'f'
f_columns = [f'{f_prefix}{i+1}' for i in range(18)]

p_prefix = 'p'
p_columns = [f'{p_prefix}{i+1}' for i in range(22)]

# Combine the 'f' and 'p' column names
new_column_names = f_columns + p_columns

# Assign the new column names to the DataFrame
df.columns = new_column_names

In [ ]:
df = df.drop(['f5'], axis=1) 
df = df.drop(['f7'], axis=1)
df = df.drop(['f9'], axis=1)
#df = df.drop(["fecha_alta"], axis=1)

In [ ]:
df = df.drop(["p22"], axis=1) 
df = df.drop(["p23"], axis=1)
#df = df.drop(["fecha_alta"], axis=1)

In [ ]:
df.info()

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split

In [ ]:
target_cols=['p1','p2','p3','p4','p5','p6','p7','p8','p9','p10','p11','p12','p13','p14','p15','p16','p17','p18','p19','p20','p21','p22']

In [ ]:
X =df.drop(target_cols, axis=1)
y =df[target_cols]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import xgboost as xgb
model = xgb.XGBClassifier(objective='multi:softprob')
model.fit(X_train, y_train)

In [ ]:
# Step 1: Concatenate all product columns into a new column 'consolidate_p'
df['consolidate_p'] = df['p1'].astype(str) + df['p2'].astype(str) +df['p3'].astype(str)

# Step 2: Calculate value counts for the 'consolidate_p' column
value_counts = df['consolidate_p'].value_counts()

In [ ]:
df['consolidate_p'] = df['p1'].astype(str) + df['p2'].astype(str) +df['p3'].astype(str)

In [ ]:
df['consolidate_p'].unique()

In [ ]:
# Step 1: Concatenate all product columns into a new column 'consolidate_p'
df['consolidate_p'] = ''
for i in range(1, 22):
    df['consolidate_p'] += df['p{}'.format(i)].astype(str)

df['consolidate_p'] =  df['consolidate_p']+df['p24'].astype(str)     
df['consolidate_p'].value_counts()

In [ ]:
classes_counts=df['consolidate_p'].value_counts()[df['consolidate_p'].value_counts()>=10000]
classes_counts

In [ ]:
df.info()

In [ ]:
filter_df = df[df['consolidate_p'].map(df['consolidate_p'].value_counts()) > 10000]
#filtered_df = df[df['consolidate_p'] > 1000]
filter_df.head()

In [ ]:
filter_df.drop(target_cols, axis=1, inplace=True)

In [ ]:
filter_df.head()

In [ ]:
le = LabelEncoder()
filter_df['consolidate_p']=le.fit_transform(filter_df['consolidate_p'])
filter_df['consolidate_p'].unique()

In [ ]:
X = filter_df.drop('consolidate_p', axis=1)
y = filter_df['consolidate_p']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import xgboost as xgb
model = xgb.XGBClassifier(objective='multi:softprob')
model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [ ]:
y_train

In [ ]:
y_train

In [ ]:
print(np.unique(X_train))

In [ ]:
(train_y)

In [ ]:
def runXGB(train_X, train_y, colsample_bytree=0.9, max_depth= 6, eta=0.05, min_child_weight=2, subsample=0.9, num_rounds=110):
    param = {}
    param['objective'] = 'multi:softprob'
    param['seed'] = 0
    param['silent'] = 0
    param['eval_metric'] = "mlogloss"
    param['booster'] = 'gbtree'
    param['num_class'] = 24
    param['colsample_bytree'] = colsample_bytree
    param['max_depth'] = max_depth 
    param['eta'] = eta
    param['min_child_weight'] = min_child_weight
    param['subsample'] = subsample
    num_round = num_rounds

    plst = list(param.items())
    xgtrain = xgb.DMatrix(train_X, label=train_y)
    model = xgb.train(plst, xgtrain, num_round)
    return model

In [ ]:
print("Building model..")
model = runXGB(X_train, y_train)
print("Predicting..")

In [ ]:
xgtest = xgb.DMatrix(test_X)
preds = model.predict(xgtest)

In [ ]:
clf = runXGB(X_train, y_train)

In [ ]:
#cols = list(df_train.drop(['target','ncodpers',"fecha_dato"], 1).columns.values)

#id_preds = defaultdict(list)
ids = df_test['ncodpers'].values

# predict model 
y_train = df_train['target']
x_train = df_train.drop(['target','ncodpers',"fecha_dato"], 1)
    
clf = runXGB(x_train, y_train)
          
x_test = df_test[cols]
x_test.fillna(0,inplace=True)
        
d_test = xgb.DMatrix(x_test)
p_test = clf.predict(d_test)
        
for id, p in zip(ids, p_test):
    id_preds[id] = list(p)

In [ ]:

xgb_model=xgb.XGBClassifier(max_depth= 6,eta=0.05,n_estimators=100,objective='multi:softprob',num_class=24)

In [ ]:
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
import numpy as np
X, y1 = make_classification(n_samples=10, n_features=100,
y2 = shuffle(y1, random_state=1)
y3 = shuffle(y1, random_state=2)
Y = np.vstack((y1, y2, y3)).T
n_samples, n_features = X.shape # 10,100
n_outputs = Y.shape[1] # 3
n_classes = 3
forest = RandomForestClassifier(random_state=1)
multi_target_forest = MultiOutputClassifier(forest, n_jobs=2)
multi_target_forest.fit(X, Y).predict(X)

In [ ]:
xgb_model.fit(X_train,y_train)

In [ ]:
def runXGB(train_X, train_y, colsample_bytree=0.9, max_depth= 6, eta=0.05, min_child_weight=2, subsample=0.9, num_rounds=110):
    param = {}
    param['objective'] = 'multi:softprob'
    param['seed'] = 0
    param['silent'] = 0
    param['eval_metric'] = "mlogloss"
    param['booster'] = 'gbtree'
    param['num_class'] = 24
    param['colsample_bytree'] = colsample_bytree
    param['max_depth'] = max_depth 
    param['eta'] = eta
    param['min_child_weight'] = min_child_weight
    param['subsample'] = subsample
    num_round = num_rounds

    plst = list(param.items())
    xgtrain = xgb.DMatrix(train_X, label=train_y)
    model = xgb.train(plst, xgtrain, num_round)
    return model

In [ ]:
cols = list(df_train.drop(['target','ncodpers',"fecha_dato"], 1).columns.values)

id_preds = defaultdict(list)
ids = df_test['ncodpers'].values

# predict model 
y_train = df_train['target']
x_train = df_train.drop(['target','ncodpers',"fecha_dato"], 1)
    
clf = runXGB(x_train, y_train)
          
x_test = df_test[cols]
x_test.fillna(0,inplace=True)
        
d_test = xgb.DMatrix(x_test)
p_test = clf.predict(d_test)
        
for id, p in zip(ids, p_test):
    id_preds[id] = list(p)

In [ ]:
df.columns = ['Status_Dt', 'Cust_ID', 'Emp_Status', 'Cust_Ctry', 'Cust_Sex', 'Age', 'Join_Dt',
                'Is_New_Cust', 'Cust_Since', 'Relship_Status','Lst_Dt_Primary_Cust', 'Cust_Type_Mth_Beg', 
                'Cust_Relship_Type_Mth_Beg', 'Residence_Ctry', 'Is_Foreigner', 'Is_Spouse_Emp', 'Join_Channel', 'Deceased_Flg', 
                'Address_Type', 'Cust_Province_Cd', 'Cust_Province_Name', 'Cust_Active_Status', 'Gross_HHLD_Income',
                'Cust_Segment', 'Savings_Acct', 'Guarantees', 'Cur_Acct', 'Derivative_Acct', 'Payroll_Acct',
                'Junior_Acct', 'Mas_Particular_Acct', 'Particular_Acct', 'Particular_Plus_Acct', 'Short_Term_Deposits',
                'Med_Term_Deposits', 'Long_Term_Deposits', 'e-Acct', 'Funds', 'Mortgage', 'Pension1', 'Loans',
                'Taxes', 'Credit_Card', 'Securities', 'Home_Acct', 'Payroll', 'Pension2', 'Direct_Debit']